@startmindmap anamnese

+ **[[StructureDefinition-anamnese-questionario.html Anamnese]]**\n""Questionnaire""
--[#White] **Já fez exame preventivo?** (30)\n""Coding""
--[#White] **Quando fez o último exame?** (31)\n""date""
--[#White] **Usa DIU?** (32)\n""Coding""
--[#White] **Está grávida?** (33)\n""Coding""
--[#White] **Uso de anticoncepcional hormonal?** (34)\n""Coding""
--[#White] **Uso de reposição hormonal?** (35)\n""Coding""
++[#White] **Já fez tratamento por radioterapia?** (36)\n""Coding""
++[#White] **Sabe a data da última menstrução/regra?** (37)\n""boolean""
++[#White] **Data da última menstrução/regra** (38)\n""date""
++[#White] **Tem ou teve algum sangramento após relações sexuais?** (39)\n""boolean""
++[#White] **Tem ou teve algum sangramento após a menopausa?** (40)\n""boolean""
++[#White] **Vacina contra HPV?** (41)\n""boolean""

@enduml