@startmindmap anamnese

+ **[[Questionnaire-anamnese-exame-citopatologico.html Anamnese]]**\n""Questionnaire""
--[#White] **Fez exame preventivo anteriormente?** (29)\n""Coding""
--[#White] **Quando fez o último exame?** (30)\n""date""
--[#White] **Usa DIU?** (31)\n""Coding""
--[#White] **Está grávida?** (32)\n""Coding""
--[#White] **Uso de anticoncepcional hormonal?** (33)\n""Coding""
--[#White] **Uso de reposição hormonal?** (34)\n""Coding""
++[#White] **Já fez tratamento por radioterapia?** (35)\n""Coding""
++[#White] **Sabe a data da última menstrução/regra?** (36)\n""boolean""
++[#White] **Data da última menstrução/regra** (37)\n""date""
++[#White] **Tem ou teve algum sangramento após relações sexuais?** (38)\n""Coding""
++[#White] **Tem ou teve algum sangramento após a menopausa?** (39)\n""Coding""
++[#White] **Vacina contra HPV?** (45)\n""Coding""

@enduml