@startuml bundle-requisicao

skinparam packagestyle rectangle 

hide circle
hide methods
hide empty members

skinparam class {
    BackgroundColor White
    ArrowColor Black
    BorderColor #505050
}

package "Bundle (requisição)\n\n<size:12>Reúne todas as informações da requisição\n" <<Node>> { 
    class Composition as "[[StructureDefinition-documento-requisicao.html Documento de requisição]]" <<Composition>>
    class ServiceRequest as "[[StructureDefinition-requisicao-exame-citopatologico.html Requisiçao de Exame Citopatológico]]" <<ServiceRequest>>
    class Paciente as "[[StructureDefinition-paciente.html Paciente]]" <<Patient>>
    class Anamnese as "[[StructureDefinition-anamnese-questionario.html Anamnese]]" <<QuestionnaireResponse>>
    class Questoes as "[[Questionnaire-anamnese-exame-citopatologico.html Questões]]" <<Questionnaire'>>
    class Exame as "[[StructureDefinition-exame-clinico.html Exame clínico]]" <<Observation>>
    class Amostra as "[[StructureDefinition-amostra-requisicao.html Amostra]]" <<Specimen>>
    Composition --> ServiceRequest
    ServiceRequest --> Paciente
    ServiceRequest --> Anamnese
    Anamnese --> Questoes
    ServiceRequest --> Exame
    ServiceRequest --> Amostra
    
}

@enduml