@startuml bundle-laudo

skinparam packagestyle rectangle 

hide circle
hide methods
hide empty members

skinparam class {
    BackgroundColor White
    ArrowColor Black
    BorderColor #505050
}

package "Bundle (laudo)\n\n<size:12>Reúne todas as informações de um laudo\n" <<Node>> { 
    class Composition as "[[StructureDefinition-documento-laudo.html Documento de laudo]]" <<Composition>>
    class DiagnosticReport as "[[StructureDefinition-diagnostico-citopatologico.html Diagnóstico citopatológico]]" <<DiagnosticReport>>
    class RequisicaoExameCitopatologico as "[[StructureDefinition-requisicao-exame-citopatologico.html Requisição de Exame Citopatológico]]" <<ServiceRequest>>
    class ReferenciaUnidadeDeSaude as "[[StructureDefinition-referencia-unidade-de-saude.html Unidade de Saúde]]" <<Reference>>
    class ReferenciaProfissional as "[[StructureDefinition-referencia-profissional.html Profissional]]" <<Reference>>
    class Amostra as "[[StructureDefinition-amostra.html Amostra]]" <<Specimen>>
    class ComponentesLaudoCitopatologico as "[[StructureDefinition-componentes-laudo-citopatologico.html Resultado]]" <<Observation>>
    Composition --> DiagnosticReport
    DiagnosticReport --> RequisicaoExameCitopatologico
    DiagnosticReport --> ReferenciaUnidadeDeSaude
    DiagnosticReport --> ReferenciaProfissional
    DiagnosticReport --> Amostra
    DiagnosticReport --> ComponentesLaudoCitopatologico
    
}

@enduml