@startuml fhir

hide circle
hide methods
hide empty members

skinparam class {
    BackgroundColor White
    ArrowColor Black
    BorderColor #505050
}

class "inspecao-colo" as InspecaoColo <<CodeSystem>> {}
class "motivo-exame" as MotivoExame <<CodeSystem>> {}
class "vs-inspecao-colo" as VsInspecaoColo <<ValueSet>> {}
class "motivos-exame" as MotivosExame <<ValueSet>> {}

VsInspecaoColo .up.> InspecaoColo
MotivosExame .up.> MotivoExame

class CPF <<NamingSystem>> {}
class "SISCAN" as SiscanProtocolo <<NamingSystem>> {}
class "Laboratório" as Laboratorio <<NamingSystem>> {}

class "Nivel Educacional" as NivelEducacional <<extension>> {
    Context: Patient
}


Enfermeira -up-> Unidade: Lotado em
Enfermeira -left-> GovBR : possui conta

Citopatologista "titular" <-down- Certificado
GovBR <-- Citopatologista: possui conta
Assinatura -left-> "1" Certificado : Feita com

@enduml