@startuml fhir

hide circle
hide methods
hide empty members

skinparam class {
    BackgroundColor White
    ArrowColor Black
    BorderColor #505050
}

class "inspecao-colo" as InspecaoColo <<CodeSystem>> {}
class "motivos-exame" as MotivosExame <<CodeSystem>> {}
class "vs-inspecao-colo" as VsInspecaoColo <<ValueSet>> {}
class "motivo-exame" as MotivoExame <<ValueSet>> {}
class "questoes-anamnese" as QuestoesAnamnese <<ValueSet>> {}

VsInspecaoColo .up.> InspecaoColo
MotivoExame .up.> MotivosExame

class CNES <<NamingSystem>> {}
class CPF <<NamingSystem>> {}
class "SISCAN" as SiscanProtocolo <<NamingSystem>> {}
class "Laboratório" as Laboratorio <<NamingSystem>> {}

class "Nivel Educacional" as NivelEducacional <<extension>> {
    Context: Patient
}

package "<<Bundle>>\nRequisição" as Bundle <<Rectangle>> {
    package "entry[0]\nComposition" as Composition <<Rectangle>> {

    }

    class "entry[1]\nRosa" as paciente {}
    class "entry[2]\nRequisição" as requisicao {}
}


@enduml