@startmindmap paciente

+ **[[StructureDefinition-paciente.html Paciente]] ** (4)\n""Patient""
--[#White] **Cartão SUS** (5)\n""identifier""
--[#White] **Nome completo** (6)\n""name""
--[#White] **[[StructureDefinition-filiacao.html Filiação]]** (7)\n""Extension""
--[#White] **Apelido** (8)\n""name""
--[#White] **CPF** (10)\n""identifier""
--[#White] **[[https://simplifier.net/redenacionaldedadosemsaude/brnacionalidade Nacionalidade]]** (11)\n""Extension (RNDS)""
--[#White] **Data de nascimento** (12)\n""birthDate""
--[#White] **[[StructureDefinition-idade.html Idade]]** (13)\n""Extension""
--[#White] **[[StructureDefinition-extension-genero.html Gênero]]** (9)\n""Extension""
--[#White] **Telefone (DDD)** (24 e 25)\n""telecom""
++[#White] **[[StructureDefinition-raca-etnia.html Raça/cor]]** (14)\n""Extension""
++[#White] **[[StructureDefinition-nivel-educacional.html Nível educacional]]** (27)\n""Extension""
++[#White] **[[StructureDefinition-endereco.html Endereço]]** (15)\n""Address""
+++[#White] **Logradouro** (16)\n""line""
+++[#White] **Número** (17)\n""line""
+++[#White] **Complemento** (18)\n""line""
+++[#White] **Bairro** (19)\n""line""
+++[#White] **Ponto de referência** (26)\n""line""
+++[#White] **UF** (20)\n""state""
+++[#White] **Codigo do município** (21)\n""city""
+++[#White] **CEP** (23)\n""postalCode""


@enduml