@startmindmap paciente

+ **Paciente**\n""Patients""
--[#White] **Cartão SUS** (7)\n""Identifier""
--[#White] **Nome completo** (8)\n""name""
--[#White] **Filiação** (9)\n""Extension""
--[#White] **Apelido** (10)\n""name""
--[#White] **CPF** (11)\n""Coding""
--[#White] **Nacionalidade** (12)\n""Extension""
--[#White] **Data de nascimento** (13)\n""birthDate""
--[#White] **Idade** (14)\n""Extension""
++[#White] **Raça/cor** (15)\n""Extension""
++[#White] **Escolaridade** (27)\n""Extension""
++[#White] **Endereço**\n""Address""
+++[#White] **Logradouro** (16)\n""line""
+++[#White] **Número** (17)\n""line""
+++[#White] **Complemento** (18)\n""line""
+++[#White] **Bairro** (19)\n""line""
+++[#White] **Ponto de referência** (26)\n""line""
+++[#White] **Codigo do município** (21)\n""city""
+++[#White] **UF** (21)\n""state""
+++[#White] **CEP** (23)\n""postalCode""


@enduml