@startmindmap requisicao

+ **[[StructureDefinition-requisicao-exame-citopatologico.html Requisiçao de Exame Citopatológico]]**\n""ServiceRequest""
--[#White] **Unidade de Saúde** (1)\n""Reference.identifier""
--[#White] **Número do protocolo** (2)\n""identifier""
--[#White] **[[StructureDefinition-identificador-prontuario.html Prontuário]]** (3)\n""Extension""
--[#White] **Motivo do exame** (28)\n""Coding""
-- **[[StructureDefinition-paciente.html Paciente]]** (4)\n""Patient""
++ **[[StructureDefinition-anamnese-questionario.html Resposta Anamnese]]** (29)\n""QuestionnaireResponse""
+++ **[[Questionnaire-anamnese-exame-citopatologico.html Questionario Anamnese]]** (29)\n""Questionnaire""
++ **[[StructureDefinition-exame-clinico.html Exame clínico]]** (42)\n""Observation""
+++[#White] **Inspeção do colo** (43)\n""Coding""
+++[#White] **Sinais sugestivos de IST?** (44)\n""boolean""
++[#White] **[[StructureDefinition-amostra-requisicao.html Amostra]]** (45)\n""Specimen""
+++[#White] **Data da coleta** (46)\n""collectedDateTime""
+++[#White] **Responsável pela coleta** (47)\n""Reference.identifier""

@enduml