id: br.gov.saude.ccu
canonical: https://fhir.fabrica.inf.ufg.br/ccu
name: CancerColoDoUtero
title: Rastreamento de Câncer de Colo de Útero
status: draft
description: >- 
  Definição de requisição e laudo de exame citopatológico, conforme INCA (Ministério da Saúde), visando interoperabilidade destas informações entre atores da saúde em todo o território nacional.

  Estas definições estabelecem o conjunto de informações a serem trocados com o Ministério da Saúde e, não necessariamente, identifica todas as informações que podem ser relevantes.

license: CC0-1.0
version: 0.0.1
fhirVersion: 4.0.1
copyright: 'Ministério da Saúde. Produzido pela UFG em parceria com o INCA.'
copyrightYear: 2022+
releaseLabel: preliminar
jurisdiction: urn:iso:std:iso:3166#BR "Brazil"
experimental: false
meta:
  lastUpdated: 2024-01-03T14:56:14Z
language: pt-BR

publisher:
  name: Comissão de Governança de Informação em Saúde (CGIS - UFG)
  url: https://cgis.ufg.br
  email: kyriosdata@ufg.br
parameters:
  apply-publisher: true
  apply-contact: true
  show-inherited-invariants: false
  active-tables: "false"

pages:
  index.md:
    title: Principal
  integrador.md:
    title: Integrador
  requisicao.md:
    title: Requisição de exame
  mapeamento.md:
    title: Mapeamento para FHIR
  resultado.md:
    title: Resultado (laudo)
  processos.md:
    title: Processos de Negócio
  requisitos.md:
  artifacts.html:
    title: Artefatos
  history.md:
    title: Histórico
  creditos.md:
    title: Créditos
  downloads.md:
    title: Baixar

menu:
  Principal: index.html
  Documentos:
    Requisitos: requisitos.html
    Processos de Negócio: processos.html
    Requisição de exame: requisicao.html
    Resultado (laudo): resultado.html
    Mapeamento FHIR: mapeamento.html
  Artefatos: artifacts.html
  Integrador: 
    Visão geral: integrador.html
    Downloads: downloads.html
  Outros:
    FHIR 4.0.1: http://hl7.org/fhir/R4/index.html
    Github: https://github.com/kyriosdata/farol
    Créditos: creditos.html
  Histórico: history.html

dependencies:
  br.ufg.cgis.rnds-lite: 0.2.1
