id: ccu
canonical: https://fhir.fabrica.inf.ufg.br/ccu
name: CancerColoDoUtero
title: "Rastreamento de Câncer de Colo de Útero"
description: "Inclui definições pertinentes ao exame citopatológico (requisição e resultado) conforme INCA, e correlatos."
status: draft
license: CC0-1.0
version: 0.1.0
fhirVersion: 4.0.1
copyrightYear: 2022+
releaseLabel: preliminar
jurisdiction: urn:iso:std:iso:3166#BR "Brazil"
experimental: false
meta:
  lastUpdated: 2021-10-22T14:56:14Z
language: pt-BR

publisher:
  name: Comissão de Governança de Informação em Saúde (CGIS - UFG)
  url: https://cgis.ufg.br
  email: kyriosdata@ufg.br
parameters:
  apply-publisher: true
  apply-contact: true
  show-inherited-invariants: false
  active-tables: "false"

pages:
  index.md:
    title: Principal
  downloads.xml:
    title: Downloads
  requisicao.md:
    title: Requisição de exame
  dominio.md:
    title: Modelagem do domínio
  resultado.md:
    title: Resultado (laudo)
  processos.md:
    title: Processos de Negócio
  requisitos.md:
  artifacts.html:
    title: Artefatos

menu:
  Principal: index.html
  Documentos:
    Requisitos: requisitos.html
    Processos de Negócio: processos.html
    Domínio: dominio.html
    Requisição de exame: requisicao.html
    Resultado (laudo): resultado.html
  Artefatos: artifacts.html
  Downloads: downloads.html
  Outros:
    FHIR: http://hl7.org/fhir/R4/index.html
    Github: https://github.com/kyriosdata/farol
  Índice: toc.html

dependencies:
  rnds.ajustes: 0.0.1
